### ISSUE TITLE
Fix "Rubocop/Metrics/CyclomaticComplexity" issue in lib/roadmapster/wizeline/roadmap.rb

### ISSUE THREAD

**Issue by iaserrat** [iaserrat/roadmapster#14]
Cyclomatic complexity for create_unit is too high. [10/6]

https://codeclimate.com/github/iaserrat/roadmapster/lib/roadmapster/wizeline/roadmap.rb#issue_59a773521e1f110001000023

**Comment by ericboehs** [comment]
Grabbing this one.
