### ISSUE TITLE
Fix "Rubocop/Performance/StringReplacement" issue in http/helpers.rb

### ISSUE THREAD

**Issue by iaserrat** [iaserrat/roadmapster#15]
Use `delete!` instead of `gsub!`.

https://codeclimate.com/github/iaserrat/roadmapster/http/helpers.rb#issue_59a773521e1f110001000021

**Comment by ericboehs** [comment]
I think this is a dup of https://github.com/iaserrat/roadmapster/issues/16

**Comment by cristina-9** [comment]
Thanks, this was a duplicate of #16 indeed.
